Repository ucsb-cs156-s24/proj-gauchoride-s24-5pm-8, pull requests merged in 2024-05, with the labels that each got.

#22 XS - BUG: User not logged in can see "Apply to be a Rider" on navbar
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5

#20 AV-Updated DriverAvailability Index Backend URL for Drivers
  frontend/src/main/pages/Drivers/DriverAvailabilityIndexPage.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityIndexPage.test.js
Labels: Ready for Staff Review

#28 AV-Created ToggleRider Feature for Rider Applications
  frontend/src/main/components/RiderApplication/RiderApplicationEditForm.js
  frontend/src/tests/components/RiderApplication/RiderApplicationEditForm.test.js
Labels: Ready for Staff Review

#29 XS - Fix Incorrect interpretation of "day" field in DriverAvailability backend
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: 10

#25 KL - FEATURE: Admin should be able to select driver from dropdown for assigning ride request
  frontend/src/main/components/Ride/RideAssignDriverForm.js
  frontend/src/tests/components/Ride/RideAssignDriverForm.test.js
  frontend/src/tests/pages/Ride/RideRequestAssignPage.test.js
Labels: 10

#30 sp-Rider can see whether their ride request is assigned or not (RE)
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/tests/components/Ride/RideTable.test.js
Labels: Ready for Staff Review

#34 AV-Created Feature for Swagger Navbar to Env Var Toggle
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: Ready for Staff Review

#23 XS - FEATURE: Improve the usability of the admin DriverAvailabiltyIndexPage
  frontend/src/main/components/Driver/DriverAvailabilityTable.js
  frontend/src/tests/components/Driver/DriverAvailabilityTable.test.js
Labels: Ready for Staff Review

#24 XS - EPIC: Improve usability of the DriverAvailabilities Create Page
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/main/pages/Drivers/DriverAvailabilityCreatePage.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityEditPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Ready for Staff Review

#33 Kl - FEATURE: Change Driver Id text fields to dropdown
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
  frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
  frontend/src/tests/pages/Shift/ShiftEditPage.test.js
Labels: 10
